import json
import os
import time
from datetime import datetime
from baseline_rag import main_app as rag_agent
from evaluation_graph import eval_app as council_of_judges

def load_test_cases(filepath="data/golden_dataset.json"):
    """Loads the golden dataset generated by Gemini."""
    actual_path = os.path.join(os.path.dirname(__file__), "../../data/golden_dataset.json")
    with open(actual_path, "r") as f:
        dataset = json.load(f)
    return dataset

def append_to_markdown_report(case_num, question, agent_answer, scores, filepath="../../data/evaluation_report.md"):
    """Saves the Council's verdict to a structured Markdown file for AI/Human review."""
    actual_path = os.path.join(os.path.dirname(__file__), filepath)
    
    # Ensure the directory exists
    os.makedirs(os.path.dirname(actual_path), exist_ok=True)
    
    # TODO: Does the chief judge actually review the verdicts and explinations of the judges?
    # Separate the Chief Judge from the Junior Council
    chief_judge_verdict = next((s for s in scores if s["judge_name"] == "CHIEF JUDGE"), None)
    junior_scores = [s for s in scores if s["judge_name"] != "CHIEF JUDGE"]

    with open(actual_path, "a", encoding="utf-8") as f:
        f.write(f"\n## Case File #{case_num}: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"**Citizen Question:** {question}\n\n")
        f.write(f"**Agent Answer:**\n> {agent_answer.replace(chr(10), chr(10)+'> ')}\n\n")
        
        f.write("### Council Member Verdicts\n")
        f.write("| Judge | Score | Rationale |\n")
        f.write("| :--- | :---: | :--- |\n")
        ## TODO: Why are are judges giving their judgement twice in a row?
        for s in junior_scores:
            # Clean up newlines in rationales so they don't break the Markdown table
            clean_rationale = s['rationale'].replace('\n', ' ')
            f.write(f"| **{s['judge_name']}** | {s['score']}/5 | {clean_rationale} |\n")
        
        if chief_judge_verdict:
            f.write("\n### ⚖️ Final Supreme Decree\n")
            f.write(f"**Chief Judge Score:** {chief_judge_verdict['score']}/5\n\n")
            f.write(f"**Ruling:** {chief_judge_verdict['rationale']}\n")
        f.write("\n---\n")

def run_automated_evaluations():
    print("="*60)
    print("⚖️ THE COUNCIL OF JUDGES IS NOW IN SESSION ⚖️")
    print("="*60)
    
    # Initialize the report file with a master header
    report_path = os.path.join(os.path.dirname(__file__), "../../data/evaluation_report.md")
    os.makedirs(os.path.dirname(report_path), exist_ok=True)
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("# 🏛️ Mega-City One: AI Evaluation Archives\n")
        f.write(f"*Session Date: {datetime.now().strftime('%Y-%m-%d')}*\n\n---\n")

    try:
        test_cases = load_test_cases()
        print(f"Loaded {len(test_cases)} test cases from the golden dataset.")
    except FileNotFoundError:
        print("🚨 Error: Could not find golden_dataset.json. Did you run generate_dataset.py first?")
        return

    for index, case in enumerate(test_cases, 1):
        question = case["question"]
        print(f"\n\n" + "-"*60)
        print(f"📁 CASE FILE #{index}: '{question}'")
        print("-"*60)
        
        print("\n[PHASE 1] The Academy Instructor is drafting an answer...")
        initial_state = {"question": question, "context": "", "answer": ""}
        agent_result = rag_agent.invoke(initial_state)
        
        if "Street Judge Decree:" in agent_result["answer"]:
            print(f"🛑 BLOCKED BY STREET JUDGE:\n{agent_result['answer']}")
            # Log the block to the markdown file
            append_to_markdown_report(index, question, agent_result['answer'], [])
            continue

        print(f"✅ AGENT'S ANSWER GENERATED.")
        time.sleep(1) 
        
        print("\n[PHASE 2] The Council is evaluating the answer...")
        eval_state = {
            "question": agent_result["question"],
            "context": agent_result["context"], 
            "answer": agent_result["answer"],
            "scores": [] 
        }
        
        config = {"configurable": {"thread_id": f"case_file_{index}"}}
        
        council_result = council_of_judges.invoke(eval_state, config=config)
        
        append_to_markdown_report(index, question, agent_result["answer"], council_result["scores"])
        print(f"💾 Case #{index} archived to evaluation_report.md")

if __name__ == "__main__":
    run_automated_evaluations()